#!/bin/bash

# this acts as a config
declare -A _app
_app["gedit"]="plain"
_app["sxiv"]="png;jpeg"
_app["zathura"]="pdf;epub+zip;zip;cbr"

# create applications array
# cheap solution
declare -A app
create_app_index(){
	for key in "${!_app[@]}"; do 
		IFS=';' read -r -a array <<< "${_app[$key]}"
		for _index in "${!array[@]}"; do
			app["${array[_index]}"]="$key"
		done
			
	done
}

check_type(){
	type=$(file --mime-type "$1" | cut -d ':' -f 2 | cut -d '/' -f 2)
	if [ $? -eq 0 ]; then
		echo "$type"
		return 0
	else
		exit 1
	fi
}


open(){
	type=$(check_type "$1")
	if [ $? -eq 0 ]; then
		"${app["$type"]}" "$1" &
	else
		exit 1
	fi
}

create_app_index
open "$1"
